### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by LordZEDith** [G-E-N-E-S-I-S/TslGame_MULTI_HACK#1]
Hey, I want to help you by making you a GUI. Would love to talk to you and learn from you. If you want examples msg me and if your interested I'll send you my skype or email :)

**Comment by bobbysn0w** [comment]
Or instead of possibly baiting him into PMs to ask for cash and to possibly scam him just submit a PR :)

**Comment by G-E-N-E-S-I-S** [comment]
just do a pull request faggot

**Comment by LordZEDith** [comment]
Didn't really mean it that way use wanted to talk about reversing in general. Sorry for the request You can delete it if you want
