### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by kkkasio** [G-E-N-E-S-I-S/TslGame_MULTI_HACK#4]
good afternoon friend !
compile to dll using visual studio, and use a dll injector?

**Comment by G-E-N-E-S-I-S** [comment]
yeah sure try that

**Comment by BerkanYildiz** [comment]
![image](https://user-images.githubusercontent.com/15068742/30349911-ea94023e-9814-11e7-80d0-53a8c0bf0f93.png)

Disable issues my dude
